

name: Daily API to DB Job

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt
    # TODO: Uncomment the following section if you need to install the ODBC driver for SQL Server
    # - name: Install ODBC Driver for SQL Server
    #   run: |
    #     sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y
    - name: Run script
      env:
        APPLICATION_KEY: ${{ secrets.APPLICATION_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
      run: python index.py
